@startuml

actor "Utilisateur connecté" as UtilisateurConnecte

package Figure {
usecase "Consulter la liste des figures" as ConsulterListeFigures
usecase "Consulter le détail d'une figure" as ConsulterDetailFigure
usecase "Créer une figure" as CreerFigure
usecase "Modifier une figure" as ModifierFigure
usecase "Supprimer une figure" as SupprimerFigure
}
package Profile {
usecase "Réinitialiser le mot de passe" as ReinitialiserMotDePasse
}

package Message {
usecase "Poster un message" as PosterMessage
usecase "Consulter l'espace de discussion" as ConsulterDiscussion


}

ConsulterListeFigures <-- UtilisateurConnecte
ConsulterDetailFigure <-- UtilisateurConnecte
CreerFigure <-- UtilisateurConnecte
ModifierFigure <-- UtilisateurConnecte
SupprimerFigure <-- UtilisateurConnecte
UtilisateurConnecte --> ConsulterDiscussion
UtilisateurConnecte --> PosterMessage
UtilisateurConnecte --> ReinitialiserMotDePasse

@enduml


